[package]
name = "globcmp-lib"
version = "0.2.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
stack-safe = ["dep:stacker"]

[dependencies]
multipeek = "0.1.2"
stacker = { version = "0.1.21", optional = true }
